language: python
script:
    - python -m pytest -v
notifications:
  slack: codewarsaw:npAF0jxCQXQBqcW3b74qxv6I
#after_success:
#    - sh .travis/deploy_dockerhub.sh
      #    - sh .travis/deploy_heroku.sh
deploy:
    provider: heroku
    api_key:
        secure: a083e6ad-dfea-4ed3-891c-496b93fc1d08
    app: damp-refuge-74606  
    on:
        repo: emilkaminski/cicd-buzz   
